environment:
  matrix:
  - TARGET: vs2008
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 9.0
    platform: Win32
    configuration: Release
  - TARGET: vs2010
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 10.0
    platform: Win32
    configuration: VSDebug
  - TARGET: vs2012
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 11.0
    platform: x64
    configuration: Release
  - TARGET: vs2013
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 12.0
    platform: Win32
    configuration: Release
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VisualStudioVersion: 14.0
    platform: Win32
    configuration: Release
  - TARGET: vs2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VisualStudioVersion: 15.0
    configuration: Release
  - TARGET: python27
  - TARGET: python36
  - TARGET: cygwin
  - TARGET: cygwin64
  - TARGET: mingw
  - TARGET: mingw-w64

install:
- cmd: git clone https://github.com/codecov/codecov-bash.git ..\codecov-bash
- cmd: git clone https://github.com/libyal/vstools.git ..\vstools
- cmd: git clone https://github.com/joachimmetz/dokan.git ..\dokan
- cmd: if [%TARGET%]==[cygwin] (
    C:\cygwin\setup-x86.exe -qgnNdO -l C:\cygwin\var\cache\setup -R c:\cygwin -s http://cygwin.mirror.constant.com -P openssl-devel -P python2-devel -P python3-devel )
- cmd: if [%TARGET%]==[cygwin64] (
    C:\cygwin64\setup-x86_64.exe -qgnNdO -l C:\cygwin64\var\cache\setup -R c:\cygwin64 -s http://cygwin.mirror.constant.com -P openssl-devel -P python2-devel -P python3-devel )

build_script:
- ps: .\synclibs.ps1
- ps: .\autogen.ps1
- cmd: if [%TARGET%]==[vs2008] (
    msbuild /verbosity:quiet msvscpp\libbde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2010] (
    set PYTHONPATH=..\vstools &&
    C:\Python27\python.exe ..\vstools\scripts\msvscpp-convert.py --no-python-dll --output-format 2010 msvscpp\libbde.sln &&
    msbuild /verbosity:quiet vs2010\libbde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2012] (
    set PYTHONPATH=..\vstools &&
    C:\Python27\python.exe ..\vstools\scripts\msvscpp-convert.py --extend-with-x64 --output-format 2012 --python-path "C:\\Python27-x64" msvscpp\libbde.sln &&
    msbuild /verbosity:quiet vs2012\libbde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2013] (
    set PYTHONPATH=..\vstools &&
    C:\Python27\python.exe ..\vstools\scripts\msvscpp-convert.py --output-format 2013 msvscpp\libbde.sln &&
    msbuild /verbosity:quiet vs2013\libbde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2015] (
    set PYTHONPATH=..\vstools &&
    C:\Python27\python.exe ..\vstools\scripts\msvscpp-convert.py --output-format 2015 msvscpp\libbde.sln &&
    msbuild /verbosity:quiet vs2015\libbde.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[vs2017] (
    set PYTHONPATH=..\vstools &&
    C:\Python27\python.exe ..\vstools\scripts\msvscpp-convert.py --extend-with-x64 --no-python-dll --output-format 2017 msvscpp\libbde.sln &&
    msbuild /verbosity:quiet vs2017\libbde.sln /property:Platform=Win32 /property:PlatformToolset=v141 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" &&
    msbuild /verbosity:quiet vs2017\libbde.sln /property:Platform=x64 /property:PlatformToolset=v141 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" )
- cmd: if [%TARGET%]==[python27] (
    C:\Python27\python.exe setup.py bdist_msi )
- cmd: if [%TARGET%]==[python36] (
    C:\Python36\python.exe setup.py bdist_msi )
- cmd: if [%TARGET%]==[cygwin] (
    xcopy /i /q /s C:\projects\libbde C:\cygwin\home\appveyor\libbde &&
    C:\cygwin\bin\bash -e -l -c "cd libbde && ./synclibs.sh --use-head && ./autogen.sh" )
- cmd: if [%TARGET%]==[cygwin64] (
    xcopy /i /q /s C:\projects\libbde C:\cygwin64\home\appveyor\libbde &&
    C:\cygwin64\bin\bash -e -l -c "cd libbde && ./synclibs.sh --use-head && ./autogen.sh" )
- cmd: if [%TARGET%]==[mingw] (
    xcopy /i /q /s C:\projects\libbde C:\MinGW\msys\1.0\home\appveyor\libbde &&
    C:\MinGW\msys\1.0\bin\bash -e -l -c "cd libbde && sed 's/@VERSION@/0.29/g' m4/pkg.m4.in > m4/pkg.m4 && ./synclibs.sh --use-head && ./autogen.sh" )
- cmd: if [%TARGET%]==[mingw-w64] (
    xcopy /i /q /s C:\projects\libbde C:\msys64\home\appveyor\libbde &&
    C:\msys64\usr\bin\bash -e -l -c "cd libbde && ./synclibs.sh --use-head && ./autogen.sh" )

test_script:
- cmd: rem Run tests
- ps: If ($env:TARGET -eq "vs2008" -or $env:TARGET -eq "vs2010" -or $env:TARGET -eq "vs2012" -or $env:TARGET -eq "vs2013" -or $env:TARGET -eq "vs2015" -or $env:TARGET -eq "vs2017") {
    .\runtests.ps1 }
- cmd: if [%TARGET%]==[cygwin] (
    C:\cygwin\bin\bash -e -l -c "cd libbde && ./runtests.sh" )
- cmd: if [%TARGET%]==[cygwin64] (
    C:\cygwin64\bin\bash -e -l -c "cd libbde && ./runtests.sh" )
- cmd: if [%TARGET%]==[mingw] (
    C:\MinGW\msys\1.0\bin\bash -e -l -c "cd libbde && ./runtests.sh" )
- cmd: if [%TARGET%]==[mingw-w64] (
    C:\msys64\usr\bin\bash -e -l -c "cd libbde && ./runtests.sh" )

after_test:
- cmd: if [%TARGET%]==[mingw] (
    copy C:\projects\codecov-bash\codecov C:\MinGW\msys\1.0\home\appveyor\libbde\codecov.sh &&
    C:\MinGW\msys\1.0\bin\bash -e -l -c "cd libbde && chmod a+x ./codecov.sh && sed -i 's/-execdir /-exec /' ./codecov.sh && ./codecov.sh -n mingw -y .codecov.yml" )

